# Generated by Django 5.2.4 on 2025-07-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image_product_rating_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
